### ISSUE TITLE
Pending Tasks

### ISSUE THREAD

**Issue by fcoronelmakingsense** [FromDoppler/doppler-webapp#2]
- [x] add `.editorconfig`
- [x] add travis configuration
- [x] research it's convenient to use sass or not
- [x] enable cors in doppler to this app
- [x] add docker configuration 
- [x] run tests in build
- [x] add prettier

**Comment by andresmoschini** [comment]
@fcoronelmakingsense @joaquinicolas I am opening the issue #6 to discuss about SASS and component's styles.
