### ISSUE TITLE
To SASS or not to SASS, that is the question

### ISSUE THREAD

**Issue by andresmoschini** [FromDoppler/doppler-webapp#6]
I am opening this issue to discuss this topic (See #2 from @fcoronelmakingsense): 

> research it's convenient to use sass or not

And @joaquinicolas said:

> What do you thing about using styled-components?
> https://github.com/styled-components/styled-components

**Comment by andresmoschini** [comment]
_styled-components_ looks nice.

Since React world is something new to most of us, I think that we should only consider alternatives widely used in React ecosystem. Is _styled-components_ one of them? 

What about a SASS based alternatives? are they common in React ecosystem?

Also, remember that we are thinking about using a CSS based CDN for global styles (maybe we could also discuss it), so all these alternatives will be for component's syles only.

@mvillaseco what do you think about _styled-components_? what alternatives do you know?

**Comment by cbernat** [comment]
I've found this article and it seems interesting https://www.reddit.com/r/reactjs/comments/8s6ga4/its_2018_why_doesnt_createreactapp_support/
React has now official support for sass.

**Comment by mvillaseco** [comment]
I don't have a strong opinion on this except for:
 - Styled Components

**Comment by joaquinicolas** [comment]
You can use props/state instead to have the component react to user actions. So instead of trying to do something fancy to change className on a component to change its appearance, you can use props directly on the component to update the style.

**Comment by joaquinicolas** [comment]
In addition, you must think in React philosophy: "break a UI down into compossible units that are represented by functions". Don't think UI as things on the screen, otherwise think It as functions hidden behind that you see.
The ideal of React is for the functions to be pure, meaning that the output will be identical for a given input. This is why isolation of a given function is desirable.
Using good, old-fashioned stylesheets, whether CSS or Sass, has been with us for twenty years. The names are global, which isn’t actually the huge problem some people make it out to be, but it still violates the ideal of isolation, and thus of pure functions.

**Comment by joaquinicolas** [comment]
One other thing, CRA( create-react-app) doesn't include SASS as a built-in module. If you want to add SASS, you'll need to run ```npm run eject``` and It's not a good deal.

**Comment by cbernat** [comment]
> One other thing, CRA( create-react-app) doesn't include SASS as a built-in module. If you want to add SASS, you'll need to run `npm run eject` and It's not a good deal.

Not anymore https://facebook.github.io/create-react-app/docs/adding-a-sass-stylesheet :)

**Comment by joaquinicolas** [comment]
> https://facebook.github.io/create-react-app/docs/adding-a-sass-stylesheet

Maybe, It is worth it for global styles.

**Comment by andresmoschini** [comment]
To put it clear, by the moment, are we agree in the usage of _styled-component_ or something similar for components, and the shared library for global styles shared with Doppler (header, buttons, paragraph, etc)?

**Comment by andresmoschini** [comment]
@mvillaseco @cbernat @fcoronelmakingsense could you confirm?

**Comment by mvillaseco** [comment]
it's OK to me.

**Comment by andresmoschini** [comment]
irodrigues   [25 minutes ago]
> Relacionado a esta cuestión de utilizar scss o css minificado estuve leyendo y averiguando para que cerremos esta confusión.
> Si CDN hostea ese .css en varios servers distribuidos y se supone que dependiendo la locación del usuario que entra a la pagina, te lo sirve desde el servidor mas cercano, esto va a optimizar la carga css por lo que si los estilos van creciendo no sea un inconveniente para la primera carga. El uso de las clases en los componentes en la aplicación no va a ser ningún problema porque lo consumis como un recurso externo.
> @mvillaseco @Cecilia Bernat @fcoronel @Gus baamonde

andresmoschini   [22 minutes ago]
> @irodrigues no entendí a que apuntás, podés dar algún ejemplo o presentar un escenario?

irodrigues   [18 minutes ago]
> Apunto a la discusión que compartiste, y les comparto lo que pienso, si el cdn lo vamos a utilizar en la aplicación de reportes, login, signup, etc. No vamos a tener problemas para llamar los estilos desde los componentes, ya que el css va a estar optimizado y la carga no va a ser un problema ya que el CDN lo soluciona.

irodrigues   [17 minutes ago]
> mas que nada porque noto que no todos pensamos lo mismo

andresmoschini   [17 minutes ago]
> osea, que proponés no usar styled-components?

irodrigues   [12 minutes ago]
> exacto, ya que vamos a utilizar la librería para extraer los recursos de estilos, me parece que lo conveniente también seria utilizarlo para los componentes, porque sino va a ser todo para componentes globales header, footer y estaria bueno centralizar..

irodrigues   [11 minutes ago]
> capaz me equivoco, y capaz soy yo el que no entendió esta parte.

andresmoschini   [9 minutes ago]
> creo que es una opción, pero que la gente que labura con react suele hacerlo de otra manera por una razón

andresmoschini   [9 minutes ago]
> al parecer muchos de los estilos están muy acoplados con los componentes
> en ese caso está bueno que estilos y componentes estén cerca
> creo que está piola dejar en el CDN lo que tiene que ver con la marca o con cosas compartidas, incluso que afecten a los componentes, por ejemplo fuentes

andresmoschini   [7 minutes ago]
> pero hay cosas que están muy acopladas y ahí es donde propongo (como la mayoría de la gente que trabaja en React) usar estilos cercanos a los componentes de react

irodrigues   [3 minutes ago]
> Ahh, claro esta bien, si es necesario tener los estilos de los componente cerca, esta perfecto que tengamos esa diferencia para manejar los estilos generales de la marca o cosas generales, pero me asusta un poco(seguro por el desconocimiento de react) que muchos estilos estén fuera de la librería. Calculo que eso lo veremos con el tiempo (edited)

andresmoschini   [2 minutes ago]
> comparto eso, creo que es un skill importante hacer que esos estilos sean compatibles y decidir que va en que lugar
> osea, no es suficiente con que un componente se vea bien

irodrigues   [2 minutes ago]
> exactamente

andresmoschini   [1 minute ago]
> estaría bueno que en el componente de react estén los estilos justos para que en un futuro si hacemos un rebranding modificando el CDN, todo siga funcional, bonito y consistente (edited)

andresmoschini   [< 1 minute ago]
> por ahí esa debería ser la euristica para decidir donde ponemos un estilo, si en el cdn o en react
